#!/bin/sh /etc/rc.common
# Copyright (C) 2011 NXP Semiconductor

START=99
PROG=SensorDataUploader.py


start_SensorDataUpload() {

    /sbin/$PROG

    return $?
}

start () {

    config_foreach start_SensorDataUpload SensorDataUploader.py

}

stop () {
    killall $PROG
}

